---
spec/spec_helper.rb:
  facterdb_string_keys: true
  mock_with: ':mocha'
  spec_overrides: "require 'spec_helper_local'"
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
    - parameter_types
